### ISSUE TITLE
Conceal does not work, till another citation is inserted

### ISSUE THREAD

**Issue by samtrek** [jalvesaq/zotcite#122]
Thank your for the update, could not make use of it for a while after moving to blink, but the recent update restored its functionality, however, their is an issue with concealing the citation. To possibly replicate
1. insert a citation, their is no concealment
2. Insert the second citation, concealment kicks in for the first but not for the second.

**Comment by jalvesaq** [comment]
I can't replicate the issue, but I believe that postponing the highlighting will fix it. Could you try the branch "fix_hl"?

**Comment by jalvesaq** [comment]
The last change in this part of zotero.py (lines 320-337) was in 2021. It's trying to find and read Zotero's `prefs.js` file to locate the directories where `zotero.sqlite` and the attachments are stored. The error message says that there is an invalid Unicode character.

**Comment by jalvesaq** [comment]
I believe that both issues you reported are fixed on the master branch.

**Comment by samtrek** [comment]
Tried setting it with

vim.g["zotcite_SQL_path"] = "/home/samtrek/Zotero/zotero.sqlite"
and also in the zotcite config file like this

return {
  "jalvesaq/zotcite",
  branch = "no_pynvim",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-telescope/telescope.nvim",
  },
  config = function()
    local opts = {
      SQL_path = "/home/samtrek/Zotero/zotero.sqlite",
    }
  end,
}

still getting this error, 
 13:25           Error           Error executing vim.schedule lua callback: ...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:446: Expected value but found T_END at character 1 stack traceback: 	[C]: in function 'get_sql_data' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:446: in function 'get_collections' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:1268: in function 'load_zotero_data' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:1446: in function 'init' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/config.lua:151: in function <...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/config.lua:145>

I think the path to the zotcite plugin files are shortened like in R.nvim, for example
data' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua
load_zotero_data' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua

where they should have been

data' 	samtrek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua
load_zotero_data' 	samtrek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua

**Comment by samtrek** [comment]
Thank you for the updated config file, having updated it to that, the error now still persists as

` 13:41           Error           Error executing vim.schedule lua callback: ...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:446: Expected value but found T_END at character 1 stack traceback: 	[C]: in function 'get_sql_data' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:446: in function 'get_collections' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:1268: in function 'load_zotero_data' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/zotero.lua:1446: in function 'init' 	...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/config.lua:151: in function <...ek/.local/share/nvim/lazy/zotcite/lua/zotcite/config.lua:145>
`

**Comment by samtrek** [comment]
yes, not worth it, could we instead get a path where we could point our zotcite plugin data files to?, in R.nvim that solved the issue from my own end before you deployed a fix.

**Comment by samtrek** [comment]
my zinfo output

12:21:54 AM msg_show.echo   Zinfo Init information
Zotero information
  banned words: "a, an, the, some, from, on, in, to, of, do, with"
  citation template: "{Authors}-{Year}"
  tmpdir: "/home/samtrek/.cache/zotcite"
  zotcite dir: "...ek/.local/share/nvim/lazy/zotcite/lua"
  types: {
  blogPost = 1,
  book = 54,
  bookSection = 49,
  computerProgram = 8,
  conferencePaper = 18,
  document = 5,
  journalArticle = 2393,
  map = 1,
  report = 4,
  thesis = 3,
  webpage = 20
}
  excluded fields: ""
  n refs: 2556
  zotero.sqlite: "/home/samtrek/Zotero/zotero.sqlite"
  docs: {}

can we have the option to set zotcite_dir, seems it is not implemented in the config and I am not able to manually set it currently it is `zotcite dir` from the above which throws error

**Comment by jalvesaq** [comment]
From the output of `:Zinfo`, zotcite seems to be working (2556 references found).

> can we have the option to set zotcite_dir, 

This option already exists: `SQL_path`.

Could you, please, delete the `zotcite` directory and let `lazny.nvim` clone it again? I forced a squash of commits some days ago, and the automatic updating of `lazy.nvim` might work.

**Comment by samtrek** [comment]
tmpdir: "/home/samtrek/.cache/zotcite"
  banned words: "a, an, the, some, from, on, in, to, of, do, with"
  data_dir: "/home/samtrek/Zotero"
  docs: {}
  n refs: 2520
  excluded fields: ""
  types: {
  blogPost = 1,
  book = 54,
  bookSection = 49,
  computerProgram = 8,
  conferencePaper = 18,
  document = 5,
  journalArticle = 2357,
  map = 1,
  report = 4,
  thesis = 3,
  webpage = 20
}
  citation template: "{Authors}-{Year}"
  zotero.sqlite: "/home/samtrek/Zotero/zotero.sqlite"
 ` zotcite dir: "...ek/.local/share/nvim/lazy/zotcite/lua"`
the "zotcite dir" is still reporting the above after setting the scripts path.

**Comment by samtrek** [comment]
Finally resolved, thank you for the effort you put into fixing the issue, and the conceal now works as it should, only able to test it after, the path issue has been fixed.
