### ISSUE TITLE
Wrong citation text if surname contains apostrophe

### ISSUE THREAD

**Issue by raffaem** [jalvesaq/zotcite#72]
If the surname of the author of the paper contains an apostrophe, the citation is rendered incorrectly, with the part after the apostrophe  rendered after the text.

Example:
```
# Introduction

This is a test

[@VH5CZE7U#D’Este_Patel_2007]

# References

<div id="refs"></div>
```

Cited paper: [link](https://www.sciencedirect.com/science/article/pii/S0048733307001199).

Output (image format):
![image](https://github.com/jalvesaq/zotcite/assets/54762742/88aa5854-c5d1-476d-b46a-0811cd1fe901)

Output (PDF format):
[test.pdf](https://github.com/jalvesaq/zotcite/files/14469169/test.pdf)

Compile command:
```
pandoc \
  -F "$ZOTREF" --citeproc \
  --pdf-engine=xelatex \
  --output="${1%%.*}.pdf" \
  "$1"
```

**Comment by jalvesaq** [comment]
It's a curly single quote... Zotcite skips ASCII single quotes, but I have to think of a way of skipping some Unicode characters. We can't simply skip non-Latin letters because the whole author's name would disappear if it were in a non-Latin script such as Greek or Chinese.

**Comment by jalvesaq** [comment]
For now, I just added a curly single quote to the list of characters to be replaced, which should fix this specific issue.

**Comment by raffaem** [comment]
Thanks for the quick response.

I don't think this fixes the issue.

I still have the same issue.

**Comment by jalvesaq** [comment]
What is your operating system and file encoding? I'm using UTF-8 on Linux. I downloaded the `.bib` from your cited paper, added it to Zotero, completed the citation key with zotcite, and generated an HTML from a Quarto document.

**Comment by raffaem** [comment]
I have arch linux and my file encoding is UTF-8.

I still get this:

![image](https://github.com/jalvesaq/zotcite/assets/54762742/bd0705f2-8183-4d60-a901-ac15fb14c87d)

have you tried compiling the markdown file I shared into a PDF with pandoc?

**Comment by raffaem** [comment]
I didn't download the bib.

I used the Zotero Connector for Firefox.

Although it looks like the same character is present.

**Comment by raffaem** [comment]
I don't know what to say.

I'm using:
```
pandoc -F "[PATH]/zotcite/python3/zotref.py" --citeproc --pdf-engine=xelatex --output="test.pdf" "test.md"
```

**Comment by jalvesaq** [comment]
This works for me:

`very_simple.qmd`:
```markdown
---
title: Exemple for zotcite
author: Your Name Here
format:
    pdf:
        filters:
            - /home/aquino/src/zotcite/python3/zotref.py
            - /home/aquino/templates/citeproc.lua
            - /home/aquino/src/zotcite/python3/abntfix.py
---

# Introduction

According to @IJDWJGM7#DEste_Patel_2007, ...

# References
```

Then:

```sh
quarto render very_simple.qmd
```

**Comment by raffaem** [comment]
> This works for me:
> 
> `very_simple.qmd`:
> 
> ```
> ---
> title: Exemple for zotcite
> author: Your Name Here
> format:
>     pdf:
>         filters:
>             - /home/aquino/src/zotcite/python3/zotref.py
>             - /home/aquino/templates/citeproc.lua
>             - /home/aquino/src/zotcite/python3/abntfix.py
> ---
> 
> # Introduction
> 
> According to @IJDWJGM7#DEste_Patel_2007, ...
> 
> # References
> ```
> 
> Then:
> 
> ```shell
> quarto render very_simple.qmd
> ```

Why you don't have the right single quote?

For me it is `[@VH5CZE7U#D’Este_Patel_2007]`, not `@IJDWJGM7#DEste_Patel_2007`.

It is what your change was supposed to do? Remove the single quote in the inline reference?

(is the whole `@IJDWJGM7#DEste_Patel_2007` called "citation key")?

**Comment by raffaem** [comment]
Oh sorry, I had to update the neovim plugin as well 😢 

It works now. Thank you very much for your support 👍🏻

**Comment by jalvesaq** [comment]
Thanks for the feedback!

> (is the whole @IJDWJGM7#DEste_Patel_2007 called "citation key")?

Yes, before the `zotref.py` filter, which deletes from "#" to the end of the citation key and inserts the whole bibliography in the YAML header. This is what `pandoc-citeproc` receives. Hence, in this example, the citation key visible to `pandoc-citeproc` is only "@IJDWJGM7".
